apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-task-run-
spec:
  serviceAccountName: pipeline
  taskRef:
    name: buildah
  params:
    - name: url
      value: https://github.com/ibm-cloud-architecture/cloudnative_sample_app
    - name: image
      value: docker.io/csantanapr/cloudnative_sample_app
