apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-build-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: test-build
  params:
    - name: image-server
      value: us.icr.io
    - name: image-namespace
      value: student01-registry
