---
apiVersion: v1
kind: ConfigMap
metadata:
  name: summarization-svc-config
data:
  WATSONX_URL: "https://eu-de.ml.cloud.ibm.com"
  PROJECT_ID: "0a9cc230-1881-4ee1-a9f0-251db933228b"
  IAM_API_KEY: "BIZxv-XvSnEi3JH1jpSHQ2vfWfl8KhSxKiz3apCIoAYb"
  WATSONX_MODEL_NAME: "ibm/granite-13b-chat-v2"
  APP_NAME: "summarization-svc"
  #AUTOWRAPT_BOOTSTRAP: instana
  IS_SAAS: "true"
  IS_OBSERVABLE: "false"
  WATSONX_CALL: "false"
  TRACELOOP_BASE_URL: "instana-agent.instana-agent:4317"
  TRACELOOP_TRACE_CONTENT: "true"
  TRACELOOP_METRICS_ENABLED: "true"
  TRACELOOP_METRICS_ENDPOINT: "otel-dc-service.hca-otel-dc-llm:30800"
  TRACELOOP_HEADERS: "api-key=DUMMY_KEY"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_METRIC_EXPORT_INTERVAL: "10000"
  WATSONX_API_BASE_URL: "https://cpd-watsonx.apps.rio.edu.ihost.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization-svc-deployment
spec:
  selector:
    matchLabels:
      app: summarization-svc-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: summarization-svc-deployment
    spec:
      containers:
      - name: summarization-svc
        image: quay.io/tncibmniceteam/genai-summarize-svc:2.1
        envFrom:
          - configMapRef:
              name: summarization-svc-config
        ports:
        - containerPort: 8090
          name: app-port
---
apiVersion: v1
kind: Service
metadata:
  name: summarization-svc-service
spec:
  ports:
  - port: 30090
    nodePort: 31900
    protocol: TCP
    name: tcp
    targetPort: app-port
  selector:
    app: summarization-svc-deployment
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: summarization-svc-route
  name: summarization-svc-route
spec:
  port:
    targetPort: tcp
  to:
    kind: Service
    name: summarization-svc-service
    weight: 100
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
